# Generated by Django 5.2.8 on 2025-11-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protips', '0002_vote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'ordering': ['-date'], 'permissions': [('can_downvote', 'Can downvote tips')]},
        ),
    ]
